### ISSUE TITLE
Goal amount resets to Zero when campaign approved

### ISSUE THREAD

**Issue by MetaHeavies** [Studio164a/Franklin#2]
Hi - I understand this theme is no longer being supported, however it seems the latest WP update breaks some core functionality - namely that when a campaign is published by the admin, the campaign goal amount resets to zero, and the campaign is listed as successful.

Would be grateful for any ideas or direction before I start going through the code to try and figure this out!

Best

Gordon

**Comment by ericnicolaas** [comment]
Hi Gordon, 

This was an issue in Appthemer Crowdfunding. You can get an updated version of the plugin that fixes this from https://github.com/Studio164a/appthemer-crowdfunding/archive/v1.9.6.zip

Cheers,
Eric

**Comment by MetaHeavies** [comment]
Cheers Eric - I appreciate you getting back so fast.

Gordon

*Faculty *is a multi-disciplinary creative agency that tells stories
through digital, experiential and film

www.fclty.com
Follow us on twitter https://twitter.com/Faculty_

London ✈ Bangkok

**Comment by ericnicolaas** [comment]
No worries. Got your email separately too, but I guess we've resolved everything here :)

**Comment by MetaHeavies** [comment]
Hey Eric

Just wanted to let you know I found a relatively minor but important bug in
the updated plugin -

The _is_funded()_ function comparing the\* current_amount\* about against the
_goal_amount_ wasn't working correctly - the\* goal_amount\* was reading as a
string (commas aren't getting stripped) not a number, so the method always
returned _true_ even if the _current_amount_ was less.

This was also true for the _percent_completed()_ function.

My quick and dirty solution was to add a small function that would remove
the comma from the *goal amount. *This could (and probably should) be set
somewhere else but I didn't actually dig into the code that much.

$goal = $this->goal(false);

$b = str_replace(',', '', $goal);

if (is_numeric($b)) {

```
$goal = $b;
```

}

Best,

Gordon

*Faculty *is a multi-disciplinary creative agency that tells stories
through digital, experiential and film

www.fclty.com
Follow us on twitter https://twitter.com/Faculty_

London ✈ Bangkok
